name: Deploy blog to GitHub Pages

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./randop.github.io

    permissions:
      contents: write

    steps:
      - name: Checkout website repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Setup Node.js
        run: pnpm env use --global lts
      - name: Install eleventy
        run: pnpm install -g @11ty/eleventy
      - name: Generate static content
        run: eleventy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master' # Only deploy on main branch
        with:
          personal_token: ${{ secrets.GIT_HUB_WORKFLOW_TOKEN }}

          # Github pages repository configuration
          external_repository: randop/randop.github.io
          publish_branch: master
          publish_dir: ./randop.github.io/_site # Directory containing the built site

          commit_message: "Deploy randop.github.io: ${{ github.sha }}"

          # add new files but leave existing ones untouched
          keep_files: true

          exclude_assets: ".git,.github"
